module Battlenet

  module Item
  
    # For now the best alternative is to use wowroster to hotlink
    Icon_url = "http://wowroster.net/Interface/Icons/"
  
    Quality = ["Poor", "Common", "Uncommon", "Rare", "Epic", "Legendary", "Artifact", "Heirloom", "Quality 8", "Quality 9"]
    
    Bind = [nil, "Binds when picked up", "Binds when equipped"]
  
    Class = ["Consumable", "Container", "Weapon", "Gem", "Armor", "Reagent", "Projectile", "Trade Goods", "Generic", "Book", 
             "Money", "Quiver", "Quest", "Key", "Permanent", "Junk", "Glyph"]
    
    InventoryType = ["None", "Head", "Neck", "Shoulder", "Shirt", "Chest", "Waist", "Legs", "Feet", "Wrist", "Hands", "Finger", 
      "Trinket", "One-Hand", "Shield", "Ranged", "Cloak", "Two-Hand", "Bag", "Tabard", "Robe", "Main Hand", 
      "Off Hand", "Held In Off-hand", "Ammo", "Thrown", "Ranged Right", "Relic"]
    
    Subclass = { # "classid","subclassid","subclassname","subclassfullname"
      0 => { 0 => [ "Consumable",nil  ],  
             1 => [ "Potion",nil  ],
             2 => [ "Elixir",nil  ], 
             3 => [ "Flask",nil  ],  
             4 => [ "Scroll",nil  ], 
             5 => [ "Food & Drink",nil  ],
             7 => [ "Bandage",nil  ],
             6 => [ "Item Enhancement",nil  ],
             8 => [ "Other",nil ]},
             
      1 => { 0 => [ "Bag",nil ],
             1 => [ "Soul Bag",nil ],
             2 => [ "Herb Bag",nil ],
             3 => [ "Enchanting Bag",nil ],
             4 => [ "Engineering Bag",nil ],
             5 => [ "Gem Bag",nil ],
             6 => [ "Mining Bag",nil ],
             7 => [ "Leatherworking Bag",nil ],
             8 => [ "Inscription Bag",nil ],
             9 => [ "Tackle Box",nil ]},
               
      2 => { 0 => [ "Axe","One-Handed Axes" ],
             1 => [ "Axe","Two-Handed Axes" ],
             2 => [ "Bow","Bows" ],
             3 => [ "Gun","Guns" ],
             4 => [ "Mace","One-Handed Maces" ],
             5 => [ "Mace","Two-Handed Maces" ],
             6 => [ "Polearm","Polearms" ],
             7 => [ "Sword","One-Handed Swords" ],
             8 => [ "Sword","Two-Handed Swords" ],
             9 => [ "Obsolete",nil ],
             10 => [ "Staff","Staves" ],
             11 => [ "Exotic","One-Handed Exotics" ],
             12 => [ "Exotic","Two-Handed Exotics" ],
             13 => [ "Fist Weapon","Fist Weapons" ],
             14 => [ "Miscellaneous",nil ],
             15 => [ "Dagger","Daggers" ],
             16 => [ "Thrown","Thrown" ],
             17 => [ "Spear","Spears" ],
             18 => [ "Crossbow","Crossbows" ],
             19 => [ "Wand","Wands" ],
             20 => [ "Fishing Pole","Fishing Poles" ]},
      
      3 => { 0 => [ "Red",nil ],
             1 => [ "Blue",nil ],
             2 => [ "Yellow",nil ],
             3 => [ "Purple",nil ],
             4 => [ "Green",nil ],
             5 => [ "Orange",nil ],
             6 => [ "Meta",nil ],
             7 => [ "Simple",nil ],
             8 => [ "Prismatic",nil ],
             9 => [ "Hydraulic",nil ],
             10 => [ "Cogwheel",nil ]},
      
      4 => { 0 => [ "Miscellaneous",nil ],
             1 => [ "Cloth","Cloth" ],
             2 => [ "Leather","Leather" ],
             3 => [ "Mail","Mail" ],
             4 => [ "Plate","Plate" ],
             5 => [ "Buckler(OBSOLETE)","Bucklers" ],
             6 => [ "Shield","Shields" ],
             7 => [ "Libram","Librams" ],
             8 => [ "Idol","Idols" ],
             9 => [ "Totem","Totems" ],
             10 => [ "Sigil","Sigils" ],
             11 => [ "Relic",nil ]},
             
      5 => { 0 => [ "Reagent",nil ]},
      
      6 => { 0 => [ "Wand(OBSOLETE)",nil ],
             1 => [ "Bolt(OBSOLETE)",nil ],
             2 => [ "Arrow",nil ],
             3 => [ "Bullet",nil ],
             4 => [ "Thrown(OBSOLETE)",nil ]},
      
      7 => { 0 => [ "Trade Goods",nil ],
             10 => [ "Elemental",nil ],
             15 => [ "Weapon Enchantment - Obsolete","Weapon Enchantment - Obsolete" ],
             5 => [ "Cloth",nil ],
             6 => [ "Leather",nil ],
             7 => [ "Metal & Stone",nil ],
             8 => [ "Meat",nil ],
             9 => [ "Herb",nil ],
             12 => [ "Enchanting",nil ],
             4 => [ "Jewelcrafting",nil ],
             1 => [ "Parts",nil ],
             3 => [ "Devices",nil ],
             2 => [ "Explosives",nil ],
             13 => [ "Materials",nil ],
             11 => [ "Other",nil ],
             14 => [ "Item Enchantment","Item Enchantment" ]},
      
      8 => { 0 => [ "Generic(OBSOLETE)",nil ]},
      
      9 => { 0 => [ "Book",nil  ],
             1 => [ "Leatherworking",nil ],
             2 => [ "Tailoring",nil ],
             3 => [ "Engineering",nil ],
             4 => [ "Blacksmithing",nil ],
             5 => [ "Cooking",nil ],
             6 => [ "Alchemy",nil ],
             7 => [ "First Aid",nil ],
             8 => [ "Enchanting",nil ],
             9 => [ "Fishing",nil ],
             10 => [ "Jewelcrafting",nil ],
             11 => [ "Inscription","Inscription" ]},
      
      10 => { 0 => [ "Money(OBSOLETE)",nil ]},
      
      11 => { 0 => [ "Quiver(OBSOLETE)",nil ],
              1 => [ "Quiver(OBSOLETE)",nil ],
              2 => [ "Quiver",nil ],
              3 => [ "Ammo Pouch",nil ]},
      
      12 => { 0 => [ "Quest",nil ]},
      
      13 => { 0 => [ "Key",nil ],
              1 => [ "Lockpick",nil ]},
      
      14 => { 0 => [ "Permanent",nil ]},
      
      15 => { 0 => [ "Junk",nil ],
              1 => [ "Reagent",nil ],
              2 => [ "Pet",nil ],
              3 => [ "Holiday",nil ],
              4 => [ "Other",nil ],
              5 => [ "Mount","Mount" ]},
      
      16 => { 1 => [ "Warrior","Warrior" ],
              2 => [ "Paladin","Paladin" ],
              3 => [ "Hunter","Hunter" ],
              4 => [ "Rogue","Rogue" ],
              5 => [ "Priest","Priest" ],
              6 => [ "Death Knight","Death Knight" ],
              7 => [ "Shaman","Shaman" ],
              8 => [ "Mage","Mage" ],
              9 => [ "Warlock","Warlock" ],
              11 => [ "Druid","Druid" ]}}
  
    Stat_table = { 1 => "Health", 2 => "Mana", 3 => "Agility", 4 => "Strength", 5 => "Intellect", 6 => "Spirit", 7 => "Stamina", 
      12 => "Defense Rating", 13 => "Dodge Rating", 14 => "Parry Rating", 15 => "Shield Block Rating", 16 => "Melee Hit Rating", 
      17 => "Ranged Hit Rating", 18 => "Spell Hit Rating", 19 => "Melee Critical Strike Rating", 20 => "Ranged Critical Strike Rating", 
      21 => "Spell Critical Strike Rating", 22 => "Melee Hit Avoidance Rating", 23 => "Ranged Hit Avoidance Rating", 24 => "Spell Hit Avoidance Rating", 
      25 => "Melee Critical Avoidance Rating", 26 => "Ranged Critical Avoidance Rating", 27 => "Spell Critical Avoidance Rating", 
      28 => "Melee Haste Rating", 29 => "Ranged Haste Rating", 30 => "Spell Haste Rating", 31 => "Hit Rating", 32 => "Critical Strike Rating", 
      33 => "Hit Avoidance Rating", 34 => "Critical Avoidance Rating", 35 => "Resilience Rating", 36 => "Haste Rating", 37 => "Expertise Rating", 
      38 => "Attack Power", 39 => "Ranged Power", 40 => "Feral Attack Power", 41 => "Damage Done", 42 => "Healing Done", 43 => "Mana Per 5 Seconds", 
      44 => "Armor Penetration Rating", 45 => "Spell Power", 46 => "Health every 5 seconds", 47 => "Spell Penetration", 48 => "Block Value"}
      
    Stat_print = {
    1 => '+%s Health',
    2 => '+%s Mana',
    3 => '+%s Agility',
    4 => '+%s Strength',
    5 => '+%s Intellect',
    6 => '+%s Spirit',
    7 => '+%s Stamina',
    46 => 'Restores %s health per 5 sec.',
    44 => 'Increases your armor penetration rating by %s.',
    38 => 'Increases attack power by %s.',
    15 => 'Increases your shield block rating by %s.',
    48 => 'Increases the block value of your shield by %s.',
    19 => 'Improves melee critical strike rating by %s.',
    20 => 'Improves ranged critical strike rating by %s.',
    32 => 'Increases your critical strike rating by %s.',
    21 => 'Improves spell critical strike rating by %s.',
    25 => 'Improves melee critical avoidance rating by %s.',
    26 => 'Improves ranged critical avoidance rating by %s.',
    34 => 'Improves critical avoidance rating by %s.',
    27 => 'Improves spell critical avoidance rating by %s.',
    #ITEM_MOD_DAMAGE_PER_SECOND_SHORT => 'Damage Per Second',
    12 => 'Increases defense rating by %s.',
    13 => 'Increases your dodge rating by %s.',
    37 => 'Increases your expertise rating by %s.',
    40 => 'Increases attack power by %s in Cat, Bear, Dire Bear, and Moonkin forms only.',
    28 => 'Improves melee haste rating by %s.',
    29 => 'Improves ranged haste rating by %s.',
    36 => 'Increases your haste rating by %s.',
    30 => 'Improves spell haste rating by %s.',
    16 => 'Improves melee hit rating by %s.',
    17 => 'Improves ranged hit rating by %s.',
    31 => 'Increases your hit rating by %s.',
    18 => 'Improves spell hit rating by %s.',
    22 => 'Improves melee hit avoidance rating by %s.',
    23 => 'Improves ranged hit avoidance rating by %s.',
    33 => 'Improves hit avoidance rating by %s.',
    24 => 'Improves spell hit avoidance rating by %s.',
    43 => 'Restores %s mana per 5 sec.',
    49 => 'Increases your mastery rating by %s.',
    14 => 'Increases your parry rating by %s.',
    39 => 'Increases ranged attack power by %s.',
    35 => 'Increases your resilience rating by %s.',
    41 => 'Increases damage done by magical spells and effects by up to %s.',
    42 => 'Increases healing done by magical spells and effects by up to %s.',
    47 => 'Increases spell penetration by %s.',
    45 => 'Increases spell power by %s.'}
  end
end